wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683634737.371217
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 19
      - 23
      4: 3.10.10
      5: 0.15.2
      8:
      - 4
      - 5
learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 64
